src/ald.c

- The filename field of entry header starts at offset 16, not 8
- Open files in binary mode

ald: Fix bugs on Windows

---

src/string.c

This fixes nunuhara/xsystem4#8.

Mimic System4.0's (strange) behavior of index access to strings

---

include/system4/ain.h
src/ain.c

- `SLBL` section contains a list of (name, address) pairs. In ain v1, the `CALLONJUMP` instruction uses this table to find destination address.
- The format of `FUNC` section is the same as in version 0.

Support ain v1 (Mamanyonyo)

---

include/system4/aar.h
meson.build
src/aar.c

AAR is an archive format used to store 3D objects and related assets, and used since Toushin Toshi 3 until Evenicle (?). (Archive files of this format have ".red" extension, but I believe "AAR" is the format name because "AARLoader.dll" loads them.)

Support AAR archives

---

src/aar.c

This fixes a file name encoding issue in Toushin Toshi 3.

aar_open: Use file_open_utf8

---

src/savefile.c

`buffer_skip()` does not reallocate when the remaining buffer is less than 4 bytes.
There seems to be the same bug in [`ex/pack.c`](https://github.com/nunuhara/alice-tools/blob/e5c7f65cf381319fd989e242c0412df0b9d1aa6e/src/core/ex/pack.c#L35) of alice-tools.

Fix a bug where gsave_write created corrupted save files

---

include/system4/savefile.h
src/savefile.c

This fixes an issue that save is extremely slow in xsystem4 on recent Android versions.

Avoid calling realloc() every time in gsave_add_*

---

include/system4/cg.h
src/cg.c
src/pms.c

It's unused, as the CG extraction functions depalettize paletted images internally.

Remove palette field from `struct cg`

---

include/system4/utfsjis.h
src/aar.c
src/archive.c
src/utfsjis.c

This makes the archive functions to equate forward slashes and backslashes when finding entries by name.
This is necessary in Daiteikoku, to access the Flash archive.
Also, fixes a bug that ``'`'`` (0x60) and `'@'` were equated.

Normalize path separators when matching archive entry names

---

src/string.c

In System4, `string[n] = 0` (where n < `string.Length()`) truncates the string to n characters.
This fixes a layout issue with text containing ruby in Shimaima.

string_set_char truncates string when character is null

---

include/system4/savefile.h
src/savefile.c

`system.ResumeWriteComment()` creates a comment-only save file if given a non-existent filename. This allows such save files to be handled by `rsave_{read/write}`.

Support resume save with only comments

---

include/system4/little_endian.h

Compilers are usually smart enough to [eliminate memcpy completely](https://godbolt.org/z/8arqonxEq).
This relies on gcc/clang's `__BYTE_ORDER__` macro for endian detection.

little_endian.h: Use memcpy() on little endian machines

---

include/system4/savefile.h
src/savefile.c

RSM v9 is used in Rance 01, Rance 03, Evenicle, etc.
Changes from RSM v7:
* Each heap object has a sequential number
* Delegate support
* RSAVE_LOCALS has a struct ("this") pointer

Add read/write support for resume save format (RSM) v9

---

include/system4/utfsjis.h
src/file.c
src/utfsjis.c

I'm going to use this in xsystem4 to implement `bgm_prepare_from_file()`, like this:
```c
#ifdef _WIN32
wchar_t *wpath = utf8_to_wchar(path);
ch->file = sf_wchar_open(wpath, SFM_READ, &ch->info);
free(wpath);
#else
ch->file = sf_open(path, SFM_READ, &ch->info);
#endif
```

Export utf8_to_wchar and wchar_to_utf8 in Win32

---

include/system4/savefile.h
src/savefile.c

Some games store meta-information such as date/time in the comment area of resume save. The save/load screen reads comments for all existing saves to display meta information, so the comments must load quickly.

rsave: Add option to read only comments

---

include/system4/afa.h
src/afa.c

Rance Quest Magnum Integrated Edition uses afa version=2 but has the numeric ID field in the file table.
The presence or absence of the ID field cannot be determined from the file header, so it needs to be determined by scanning the file table.

afa: support Rance Quest Magnum Integrated Edition

---

include/system4/ald.h
src/ald.c

ALD archives in downloadable edition of some games are obfuscated by adding a fixed value to the first 3 bytes of the archive. Since this magic number varies from game to game, this change scans the pointer table to determine the correct value of the first 3 bytes, and then calculates the magic number from there.
This logic has been used at https://xsystem4-pwa.web.app/ for 9 months and no problems have been reported.

ald: Magic number detection

---

meson.build
src/file.c

In macOS/iOS file systems (HFS+ and APFS), file names are stored in Unicode NFD (Normalization Form Decomposed). For example, U+304C (HIRAGANA LETTER GA) is converted to two characters, U+304B (HIRAGANA LETTER KA) and U+3099 (COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK).
This is problematic for file name comparisons, so this change makes `readdir_utf8()` normalize file names to NFC on Apple platforms and WebAssembly.

readdir_utf8: Normalize file names to NFC on Apple platforms

---

include/system4/fnl.h
src/fnl.c

Fnl file can be large (240MB in Daiteikoku), so this makes `fnl_open()` read only the index into memory, and `fnl_glyph_data()` read the glyph data from the file as needed.

fnl: Do not load entire fnl file into memory

---

src/file.c

`normalize_to_nfc()` must be defined, as it is used by `path_get_icase()`.

Fix Windows build

---

src/file.c

This may simplify subsequent processing on the caller side.

Make realpath_utf8() convert '\\' to '/' on Windows

---

src/qnt.c

The lightmap textures for Rance 6 and GALZOO Island are QNT images that only contain an alpha channel, with no pixel data.
The existing code attempted to call `extract_pixel` on these files, which in turn would try to uncompress an empty buffer, leading to a `WARNING()`.

QNT: Handle alpha-only images correctly

---

include/system4/flat.h
src/flat.c

Adds parsing for the MTLC section and implements parsing for Script and Graphic timelines. There is a Sound timeline as well but I have not found a flat that uses it so it remains unimplemented.
- Replace `uk2` with `version` (V1/V2)
- Read `version` first for V2; move `uk1` to the trailing slot
- Implement reader for MTLC payloads (uncompressed and zlib-compressed when `fh.version >= 4`).
- Add 4-byte-aligned Pascal string helper
- Support v<15: one key per frame.
- Support v>=15: **per-frame key counts** with allocations per frame. Though in most cases there is only one key.
- Version-aware key size (92/96/100 bytes) and field gating (`uk1`, `uk2`).
- Implement key reader with opcode: 0 = end, 1 = jump_frame, 2 = stop, 3 = string payload
Parsed ~2000 `.flat` files from 2014–2018 with no …

FLAT: parse MTLC section
